<a href="https://colab.research.google.com/github/tnrcelik/assignment/blob/main/Taner_Assignment_1_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [43]:
import numpy as np


#### 2. Create an array from my_list=[5,10,15,20,25]

In [44]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [ ]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [45]:
a= np.ones((4,4), dtype=int)
a[0:4] = 7
a

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [ ]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [46]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [ ]:
np.linspace(0, 24,25).astype(int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [ ]:
np.random.rand(5)

array([0.54627568, 0.31310039, 0.01071228, 0.72926606, 0.14212985])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [ ]:
np.random.random((5,5))

array([[0.77266517, 0.27285804, 0.36581281, 0.01177776, 0.34365157],
       [0.62545665, 0.1809078 , 0.31863179, 0.21584843, 0.05025814],
       [0.60598132, 0.35440251, 0.34899882, 0.79757116, 0.66445843],
       [0.13166794, 0.6113398 , 0.429726  , 0.58982057, 0.21329279],
       [0.31779675, 0.80467922, 0.49742291, 0.035021  , 0.16981026]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [47]:
v = np.random.randint(20,50,size=(3,4))
v



array([[30, 25, 41, 21],
       [45, 40, 46, 32],
       [37, 44, 21, 33]])

#### 13. Reshape the array below with the shape of 6x8

In [ ]:
np.reshape(v, (6, 8)) 

In [ ]:
#reshape with -1
v.reshape(-1)


array([20, 44, 47, 41, 46, 25, 47, 49, 42, 48, 29, 29])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat= np.arange(0,100).reshape(10,10)

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [49]:
mat= np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### 15. Get the first column of the array above.

In [ ]:
a = mat[:,0]
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
b = mat[2,:]
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat[:,2] = 77
mat

array([[ 0,  1, 77,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 77, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 77, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 77, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 77, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 77, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 77, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 77, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 77, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 77, 93, 94, 95, 96, 97, 98, 99]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [50]:
mat[(1,3),(0,1)]

array([10, 31])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
mat[2:,1:]

array([[21, 77, 23, 24, 25, 26, 27, 28, 29],
       [31, 77, 33, 34, 35, 36, 37, 38, 39],
       [41, 77, 43, 44, 45, 46, 47, 48, 49],
       [51, 77, 53, 54, 55, 56, 57, 58, 59],
       [61, 77, 63, 64, 65, 66, 67, 68, 69],
       [71, 77, 73, 74, 75, 76, 77, 78, 79],
       [81, 77, 83, 84, 85, 86, 87, 88, 89],
       [91, 77, 93, 94, 95, 96, 97, 98, 99]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat
x = mat[mat<10]
y = mat[mat>12]
m = sum(x)+ sum(y)
m

5229

#### 21. Get the standard deviation of the result above

In [ ]:
np.std(mat)

28.578838324886476

#### 22. Get the sum of the second column from array above

In [ ]:
#print array here
mat

array([[ 0,  1, 77,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 77, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 77, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 77, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 77, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 77, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 77, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 77, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 77, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 77, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
column_sums = mat[:, 1].sum()
print(column_sums)

460


#### 23. Get the median, mean and std of 3rd row from array above

In [51]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[2]

array([20, 21, 77, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#median
row2_median = np.median(mat[2])
print(row2_median)


25.5


In [ ]:
#mean
row2_mean = np.mean(mat[2])
print(row2_mean)

30.0


In [52]:
#std
row2_std = np.std(mat[2])
print(row2_std)

2.8722813232690143


# Pandas Section

In [ ]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [55]:
sal=pd.read_csv('Salaries.csv')

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [56]:
sal.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [57]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year values are there?**

In [134]:
 dif_year = sal.groupby("Year")
 dif_year.count()
 

Id  EmployeeName  JobTitle  BasePay  OvertimePay  OtherPay  Benefits  \
Year                                                                            
2011  36159         36159     36159    36159        36159     36159         0   
2012  36766         36766     36766    36766        36766     36766     36766   
2013  37606         37606     37606    37001        37606     37606     37606   
2014  38123         38123     38123    38119        38119     38119     38119   

      TotalPay  TotalPayBenefits  Notes  Agency  Status   day3  
Year                                                            
2011     36159             36159      0   36159       0  20312  
2012     36766             36766      0   36766       0  20050  
2013     37606             37606      0   37606       0  18911  
2014     38123             38123      0   38123       0  19891

In [ ]:
#Print out max and avg TotalPay
#max
max_TotalPay = sal['TotalPay'].max()
max_TotalPay


567595.43

In [ ]:
#avg
avg_TotalPay = sal['TotalPay'].mean()
avg_TotalPay


74768.321971703

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [ ]:
limit = sal['TotalPay'].mean()
column_name = 'TotalPay'
column = sal[column_name]
count = column[column > limit].count()
count


69489

**How much does ALBERT PARDINI make (including benefits)?**

In [58]:
 sal[sal['EmployeeName']=='ALBERT PARDINI']['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is the lowest paid person?**

In [ ]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [ ]:
uniques = sal['JobTitle'].unique()
uniques

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

In [59]:
sal['JobTitle'].iloc[-3:]

148651                  Not provided
148652                  Not provided
148653    Counselor, Log Cabin Ranch
Name: JobTitle, dtype: object

**How many people earned more than avg in 2012?**

In [ ]:
df=sal.loc[([sal['Year'] ==2012] >[sal['Year'] ==2012].mean())
df

In [95]:
TotalPay_2012 = sal[sal['Year'] ==2012]
TotalPay_2012

Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
72920  72921                 100                  Junior Clerk     -30.58   
72921  72922                 100               General Laborer       0.00   
72922  72923                 100                         Clerk      -9.50   
72923  72924                 100                 Special Nurse       0.00   
72924  72925                 100              Transit Operator       0.00   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
72920        45.87      0.00      1.36      15.29             16.65  2012   
72921         0.00      0.00     12.90       0.00             12.90  2012   
72922        14.25      0.00      0.42       4.75              5.17  2012   
72923         0.00      3.28      0.88       3.28              4.16  2012   
72924         0.00      1.77      0.14       1.77              1.91  2012   

       Notes         Agency  Status   day3  
36159    NaN  San Francisco     NaN    NaN  
36160    NaN  San Francisco     NaN    NaN  
36161    NaN  San Francisco     NaN    NaN  
36162    NaN  San Francisco     NaN    NaN  
36163    NaN  San Francisco     NaN    NaN  
...      ...            ...     ...    ...  
72920    NaN  San Francisco     NaN  100.0  
72921    NaN  San Francisco     NaN  100.0  
72922    NaN  San Francisco     NaN  100.0  
72923    NaN  San Francisco     NaN  100.0  
72924    NaN  San Francisco     NaN  100.0  

[36766 rows x 14 columns]

In [ ]:
#How many people have a title of Manager in their jobs?
#use apply function here
def chief_string(title):
    if 'manager' in title.lower().split():
        return True
    else:
        return False
    
sal['JobTitle'].apply(lambda x: chief_string(x))
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))


4056

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [67]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  day3  
0  2011    NaN  San Francisco     NaN   NaN  
1  2011    NaN  San Francisco     NaN   NaN  
2  2011    NaN  San Francisco     NaN   NaN  
3  2011    NaN  San Francisco     NaN   NaN  
4  2011    NaN  San Francisco     NaN   NaN

In [66]:
sal_new= sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [65]:
sal_new= sal.loc[:,['JobTitle','BasePay',	'OvertimePay',	'OtherPay',	'Benefits',	'TotalPay']]
sal_new

JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  
0              0.00  400184.25       NaN  567595.43  
1         245131.88  137811.38       NaN  538909.28  
2         106088.18   16452.60       NaN  335279.91  
3          56120.71  198306.90       NaN  332343.61  
4           9737.00  182234.59       NaN  326373.19  
...             ...        ...       ...        ...  
148649         0.00       0.00       0.0       0.00  
148650          NaN        NaN       NaN       0.00  
148651          NaN        NaN       NaN       0.00  
148652          NaN        NaN       NaN       0.00  
148653         0.00    -618.13       0.0    -618.13  

[148654 rows x 6 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [101]:
average_TotalPay = sal['TotalPay'].mean()
min_TotalPay = sal['TotalPay'].min()

df2=sal.loc[(sal['TotalPay'] > min_TotalPay) & (sal['TotalPay'] < average_TotalPay)]

print(df2) 

            Id EmployeeName                          JobTitle   BasePay  \
15847    15848          100     ELIGIBILITY WORKER SUPERVISOR  73155.87   
15848    15849          100              AUTOMOTIVE MACHINIST  73554.60   
15849    15850          100  SENIOR FARE COLLECTIONS RECEIVER  64694.49   
15850    15851          100                            PORTER  48472.40   
15851    15852          100                  WATERSHED KEEPER  60206.62   
...        ...          ...                               ...       ...   
148648  148649          100                         Custodian      0.00   
148649  148650          100                         Custodian      0.00   
148650  148651          100                      Not provided       NaN   
148651  148652          100                      Not provided       NaN   
148652  148653          100                      Not provided       NaN   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
15847          0.00   

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___