___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [138]:
import numpy as np


#### 2. Create an array from my_list=[5,10,15,20,25]

In [139]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [140]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [141]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [142]:
a= np.ones((4,4), dtype=int)
a[0:4] = 7
a

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [143]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [144]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [145]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [146]:
np.linspace(0, 24,25).astype(int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [147]:
np.random.rand(5)

array([0.60927022, 0.95734593, 0.52747981, 0.62886421, 0.28343831])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [148]:
np.random.random((5,5))

array([[0.36439928, 0.63729546, 0.2562708 , 0.74525319, 0.43808576],
       [0.98706954, 0.8043105 , 0.03036159, 0.99988831, 0.73389561],
       [0.02771122, 0.94200562, 0.30288326, 0.78903499, 0.57344042],
       [0.08870636, 0.72802194, 0.55067206, 0.46907382, 0.7025766 ],
       [0.27374114, 0.38050593, 0.2067626 , 0.91823854, 0.53904763]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [152]:
v = np.random.randint(20,50,size=(3,4))
v



array([[24, 42, 21, 39],
       [35, 47, 30, 39],
       [33, 30, 38, 47]])

#### 13. Reshape the array below with the shape of 6x8

In [157]:
np.reshape(v, (6, 8)) 

ValueError: ignored

In [158]:
#reshape with -1
v.reshape(-1)


array([24, 42, 21, 39, 35, 47, 30, 39, 33, 30, 38, 47])

## Numpy Indexing and Selection


In [159]:
#Create array below
mat= np.arange(0,100).reshape(10,10)

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [160]:
mat= np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### 15. Get the first column of the array above.

In [161]:
a = mat[:,0]
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### 16. Get the values in 2nd row for every 2 step.

In [162]:
b = mat[2,:]
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### 17.Assign 77 to every cell in 3rd column.

In [163]:
mat[:,2] = 77
mat

array([[ 0,  1, 77,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 77, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 77, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 77, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 77, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 77, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 77, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 77, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 77, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 77, 93, 94, 95, 96, 97, 98, 99]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [164]:
mat[(1,3),(0,1)]

array([10, 31])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [165]:
mat[2:,1:]

array([[21, 77, 23, 24, 25, 26, 27, 28, 29],
       [31, 77, 33, 34, 35, 36, 37, 38, 39],
       [41, 77, 43, 44, 45, 46, 47, 48, 49],
       [51, 77, 53, 54, 55, 56, 57, 58, 59],
       [61, 77, 63, 64, 65, 66, 67, 68, 69],
       [71, 77, 73, 74, 75, 76, 77, 78, 79],
       [81, 77, 83, 84, 85, 86, 87, 88, 89],
       [91, 77, 93, 94, 95, 96, 97, 98, 99]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [166]:
mat
x = mat[mat<10]
y = mat[mat>12]
m = sum(x)+ sum(y)
m

5229

#### 21. Get the standard deviation of the result above

In [167]:
np.std(mat)

28.578838324886476

#### 22. Get the sum of the second column from array above

In [168]:
#print array here
mat

array([[ 0,  1, 77,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 77, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 77, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 77, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 77, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 77, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 77, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 77, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 77, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 77, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
column_sums = mat[:, 1].sum()
print(column_sums)

460


#### 23. Get the median, mean and std of 3rd row from array above

In [169]:
mat

array([[ 0,  1, 77,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 77, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 77, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 77, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 77, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 77, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 77, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 77, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 77, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 77, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
mat[2]

array([20, 21, 77, 23, 24, 25, 26, 27, 28, 29])

In [171]:
#median
row2_median = np.median(mat[2])
print(row2_median)


25.5


In [172]:
#mean
row2_mean = np.mean(mat[2])
print(row2_mean)

30.0


In [173]:
#std
row2_std = np.std(mat[2])
print(row2_std)

15.905973720586866


# Pandas Section

In [174]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [175]:
sal=pd.read_csv('Salaries.csv')

In [176]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [177]:
sal.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [178]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year values are there?**

In [179]:
 dif_year = sal.groupby("Year")
 dif_year.count()
 

Id  EmployeeName  JobTitle  BasePay  OvertimePay  OtherPay  Benefits  \
Year                                                                            
2011  36159         36159     36159    36159        36159     36159         0   
2012  36766         36766     36766    36766        36766     36766     36766   
2013  37606         37606     37606    37001        37606     37606     37606   
2014  38123         38123     38123    38119        38119     38119     38119   

      TotalPay  TotalPayBenefits  Notes  Agency  Status  
Year                                                     
2011     36159             36159      0   36159       0  
2012     36766             36766      0   36766       0  
2013     37606             37606      0   37606       0  
2014     38123             38123      0   38123       0

In [180]:
#Print out max and avg TotalPay
#max
max_TotalPay = sal['TotalPay'].max()
max_TotalPay


567595.43

In [181]:
#avg
avg_TotalPay = sal['TotalPay'].mean()
avg_TotalPay


74768.321971703

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [182]:
limit = sal['TotalPay'].mean()
column_name = 'TotalPay'
column = sal[column_name]
count = column[column > limit].count()
count


69489

**How much does ALBERT PARDINI make (including benefits)?**

In [183]:
 sal[sal['EmployeeName']=='ALBERT PARDINI']['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is the lowest paid person?**

In [184]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [185]:
uniques = sal['JobTitle'].unique()
uniques

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

In [186]:
sal['JobTitle'].iloc[-3:]

148651                  Not provided
148652                  Not provided
148653    Counselor, Log Cabin Ranch
Name: JobTitle, dtype: object

**How many people earned more than avg in 2012?**

In [223]:
[sal.groupby ('Year').mean()]["TotalPay"], ["EmployeeName"]

TypeError: ignored

In [198]:
#How many people have a title of Manager in their jobs?
#use apply function here
def chief_string(title):
    if 'manager' in title.lower().split():
        return True
    else:
        return False
    
sal['JobTitle'].apply(lambda x: chief_string(x))
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))


4056

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [100]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

     Year  Notes         Agency  Status  
0  2011.0    NaN  San Francisco     NaN  
1  2011.0    NaN  San Francisco     NaN  
2  2011.0    NaN  San Francisco     NaN  
3  2011.0    NaN  San Francisco     NaN  
4  2011.0    NaN  San Francisco     NaN

In [101]:
sal_new= sal.iloc[:,[0,1,2,7,8]]
sal_new

Id         EmployeeName  \
0          1       NATHANIEL FORD   
1          2         GARY JIMENEZ   
2          3       ALBERT PARDINI   
3          4    CHRISTOPHER CHONG   
4          5      PATRICK GARDNER   
...      ...                  ...   
19918  19919    STEPHANI THOMPSON   
19919  19920      CYNTHIA VASQUEZ   
19920  19921       SANDA WIN THAW   
19921  19922  CHARLES BRIDGEWATER   
19922  19923      DIMITRI SHIKALO   

                                             JobTitle   TotalPay  \
0      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                     CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                     CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4        DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                               ...        ...   
19918                                 PRINCIPAL CLERK   63538.40   
19919                           EXECUTIVE SECRETARY I   63538.40   
19920             MENTAL HEALTH REHABILITATION WORKER   63536.37   
19921                                  ASPHALT WORKER   63534.97   
19922                                             NaN        NaN   

       TotalPayBenefits  
0             567595.43  
1             538909.28  
2             335279.91  
3             332343.61  
4             326373.19  
...                 ...  
19918          63538.40  
19919          63538.40  
19920          63536.37  
19921          63534.97  
19922               NaN  

[19923 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [102]:
sal_new= sal.loc[:,['JobTitle','BasePay',	'OvertimePay',	'OtherPay',	'Benefits',	'TotalPay']]
sal_new

JobTitle    BasePay  OvertimePay  \
0      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                     CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                     CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3                WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4        DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   
...                                               ...        ...          ...   
19918                                 PRINCIPAL CLERK   63538.40         0.00   
19919                           EXECUTIVE SECRETARY I   63538.40         0.00   
19920             MENTAL HEALTH REHABILITATION WORKER   58689.87      3398.39   
19921                                  ASPHALT WORKER   57408.59      3227.92   
19922                                             NaN        NaN          NaN   

        OtherPay  Benefits   TotalPay  
0      400184.25       NaN  567595.43  
1      137811.38       NaN  538909.28  
2       16452.60       NaN  335279.91  
3      198306.90       NaN  332343.61  
4      182234.59       NaN  326373.19  
...          ...       ...        ...  
19918       0.00       NaN   63538.40  
19919       0.00       NaN   63538.40  
19920    1448.11       NaN   63536.37  
19921    2898.46       NaN   63534.97  
19922        NaN       NaN        NaN  

[19923 rows x 6 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [202]:
average_TotalPay = sal['TotalPay'].mean()
min_TotalPay = sal['TotalPay'].min()

In [215]:
((sal[["EmployeeName","TotalPay"]]) < average_TotalPay) & ((sal[["EmployeeName","TotalPay"]]) > min_TotalPay)

TypeError: ignored

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___